### ISSUE TITLE
Increase animal HP

### ISSUE THREAD

**Issue by paxmeny** [ConnorCurry/Wildlife-Simulator#16]

**Comment by paxmeny** [comment]
When healed, an animals HP is increased relative to the heal amount. Each animal has a maximum HP that they cannot heal past.

How to demo: Have a battle where the players animal is damaged. Afterwards, heal for an amount such that afterwards the animals HP is still not full. Heal them again, now for an amount that would make the animal heal for an amount such that that amount plus its current HP is greater than this animals maximum HP. Now make sure that the animals HP did not surpass its maximum.

**Comment by rsdoane** [comment]
Actual time took 1 hour
