### ISSUE TITLE
Swap Animals

### ISSUE THREAD

**Issue by ConnorCurry** [ConnorCurry/Wildlife-Simulator#8]
Swapping uses up the player's turn in battle by swapping animals.
This swap always happens before attacks in the turn. 
If the opponent attacks in that turn, it will hit the new animal that has been swapped in to replace the old.
The fight continues as normal in the next turn.

How to Demo
When a player wants to swap animals, they run the swap animal function, and select a new animal from their current party.
The new animal will be swapped in and the opponent will get one free attack on them.

Test that when swapping animals, both the outgoing and incoming animals maintain their health and status effects.
Test that user should only be able to swap in animals from their current party.

**Comment by eostendarp** [comment]
Stuck because Battle currently doesn't support non attacking moves

Should Swap animal be a non-damaging move each animal has, or an alternative option presented in Battle?

**Comment by eostendarp** [comment]
~2 actual hours
