### ISSUE TITLE
Capture Wild Animal

### ISSUE THREAD

**Issue by ConnorCurry** [ConnorCurry/Wildlife-Simulator#9]
How to Demo
When in a wild battle, a player will attempt to capture the wild animal.
This capture rate is determined by the animal, its level, and its health.
If successfully captured the battle ends and the wild animal is added to the player's collection of animals.
If unsuccessful, the battle continues and the wild animal gets to freely attack the player once, as the player sacrificed their turn to attempt capture.

**Comment by jstark523** [comment]
Begin animal class
